#!/bin/bash
# Title:        ClamAV Scan Scheduled Run Script
# Description:  This script updates and runs Clam AV scanning on a regular
#               basis. It also sends an email report to the web server
#               administrator.
# Author:       Ryan Gatchalian
# Date Created: 2015-Dec-02
# Date Updated: 2015-Dec-02
# Version:      1.0

##### CONSTANTS #####
WEB_SERVER_ADMIN_EMAIL=admin@example.com

##### BEGIN SCRIPT #####

# STEP 1: Run ClamAV scanner (freshclam)
( /usr/local/cpanel/3rdparty/bin/freshclam ) | mail -s 'Clam AV Daily Scan Report' $WEB_SERVER_ADMIN_EMAIL

##### END SCRIPT #####
