#!/bin/bash
# Title:       chkrootkit Scheduled Run Script
# Description: This script updates and runs chkrootkit on a regular
#              basis. It also sends an email report to the web server
#              administrator.
# Author:      Ryan Gatchalian
# Date:        2015-June-09
# Version:     1.0

##### CONSTANTS #####
WEB_SERVER_ADMIN_EMAIL=admin@example.com

##### BEGIN SCRIPT #####

# STEP 1: Run chkrootkit
( /usr/local/bin/chkrootkit ) | mail -s 'chkrootkit Daily Scan Report' $WEB_SERVER_ADMIN_EMAIL

##### END SCRIPT #####
