#!/bin/bash
# Title:        Server Services Disable Script
# Description:  This script disables unnecessary services as recommended by
#               ConfigServer Firewall (CSF).
# Author:       Ryan Gatchalian
# Date Created: 2015-Jun-15
# Date Updated: 2016-Feb-26
# Version:      1.0

##### BEGIN SCRIPT #####

# STEP 1: Disable nfslock service
echo 'Disabling nfslock service...'
service nfslock stop
chkconfig nfslock off

# STEP 2: Disable portreserve service
echo 'Disabling portreserve service...'
service portreserve stop
chkconfig portreserve off

# STEP 3: Disable rpcbind service
echo 'Disabling rpcbind service...'
service rpcbind stop
chkconfig rpcbind off

# STEP 4: Disable xinetd service
echo 'Disabling xinetd service...'
service xinetd stop
chkconfig xinetd off

##### END SCRIPT #####
