#!/bin/bash
# Title:        Kernel Update Script
# Description:  This script updates the current CentOS Linux kernel.
# Author:       Ryan Gatchalian
# Date Created: 2015-Jun-17
# Date Updated: 2015-Dec-17
# Version:      1.0

##### CONSTANTS #####
WEB_SERVER_ADMIN_EMAIL=admin@example.com

##### BEGIN SCRIPT #####

# STEP 1: Update Linux kernel
(
echo 'Updating Linux kernel...'
yum update -y

# STEP 2: Perform a graceful reboot
echo 'Rebooting...'
reboot
) | mail -s 'CentOS Kernel Update Report' $WEB_SERVER_ADMIN_EMAIL

##### END SCRIPT #####
