#!/bin/bash
# Title:        YUI Compressor Download Script
# Description:  This script downloads the latest version of the YUI Compressor
#               from the official GitHub repository.
# Author:       Ryan Gatchalian
# Date Created: 2015-May-27
# Date Updated: 2015-Dec-23
# Version:      1.0

##### CONSTANTS #####
USER_LIB_DIR=/usr/local/lib
YUI_COMPRESSOR_VERSION=2.4.8
YUI_COMPRESSOR_LIB_DIR=$USER_LIB_DIR/yuicompressor

##### FUNCTIONS #####
download_yui_compressor()
{
    # STEP 1: Go into the $YUI_COMPRESSOR_LIB_DIR directory
    echo "Going into the $YUI_COMPRESSOR_LIB_DIR directory..."
    cd $YUI_COMPRESSOR_LIB_DIR

    # STEP 2: Download YUI Compressor
    echo 'Downloading YUI Compressor...'
    wget https://github.com/yui/yuicompressor/releases/download/v$YUI_COMPRESSOR_VERSION/yuicompressor-$YUI_COMPRESSOR_VERSION.jar -O yuicompressor-$YUI_COMPRESSOR_VERSION.jar
}

##### BEGIN SCRIPT #####

if [ -d "$USER_LIB_DIR" ]
then
    # Control will enter here if $USER_LIB_DIR exists
    echo "Directory $USER_LIB_DIR already exists."

    # STEP 1: Remove previous versions of YUI Compressor
    echo 'Removing previous versions of YUI Compressor...'
    rm -rf $USER_LIB_DIR/yuicompressor-*

    if [ -d "$YUI_COMPRESSOR_LIB_DIR" ]
    then
        # Control will enter here if $YUI_COMPRESSOR_LIB_DIR exists
        echo "Directory $YUI_COMPRESSOR_LIB_DIR already exists."
        echo 'Removing previous versions of YUI Compressor...'
        rm -rf $YUI_COMPRESSOR_LIB_DIR/yuicompressor-*
    else
        # STEP 2: Create $YUI_COMPRESSOR_LIB_DIR directory
        echo "Creating $YUI_COMPRESSOR_LIB_DIR directory..."
        mkdir $YUI_COMPRESSOR_LIB_DIR
    fi

    # STEP 3: Download YUI Compressor
    download_yui_compressor
else
    # STEP 1: Create $USER_LIB_DIR directory
    echo "Creating $USER_LIB_DIR directory..."
    mkdir $USER_LIB_DIR

    # STEP 2: Create $YUI_COMPRESSOR_LIB_DIR directory
    echo "Creating $YUI_COMPRESSOR_LIB_DIR directory..."
    mkdir $YUI_COMPRESSOR_LIB_DIR

    # STEP 3: Download YUI Compressor
    download_yui_compressor
fi

##### END SCRIPT #####
